version: "3.8"

services:
  dnsmasq:
    image: tschaffter/dnsmasq:2.85
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq.d/example.com.conf:/etc/dnsmasq.d/example.com.conf:ro
    command: ["dnsmasq", "-k", "--server", "1.1.1.1", "--server", "1.0.0.1"]
    networks:
     - dns
    ports:
     - "53:53/udp"
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  dns: