version: "3.8"

services:
  dnsmasq:
    image: tschaffter/dnsmasq:2.80
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_HOST=8.8.8.8
      - SERVER_PORT=53
    networks:
     - dns
    ports:
     - "53:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq.d/example.com.conf:/etc/dnsmasq.d/example.com.conf:ro
      - ./hosts.conf:/etc/hosts.conf:ro

networks:
  dns: